#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
语言资源管理工具
负责管理应用的多语言支持
"""

from typing import Dict, List, Callable, Any

class LanguageUtils:
    """语言资源管理类"""
    
    def __init__(self, default_language: str = 'zh_CN') -> None:
        """
        初始化语言资源
        :param default_language: 默认语言代码
        """
        self.current_language: str = default_language
        self.language_resources: Dict[str, Dict[str, str]] = {}
        self._init_language_resources()
        # 初始化语言变化事件订阅者列表
        self._subscribers: List[Callable[[str], None]] = []
    
    def _init_language_resources(self) -> None:
        """
        初始化语言资源字典
        """
        self.language_resources = {
            'zh_CN': {
                'window_title': '水电费抄收管理系统',
                'menu_dashboard': '概览',
                'menu_tenant': '租户管理',
                'menu_meter': '水电表管理',
                'menu_reading': '抄表管理',
                'menu_charge': '计费管理',
                'menu_payment': '收费管理',
                'menu_settlement': '结算管理',
                'menu_price': '价格管理',
                'menu_report': '报表管理',
                'menu_user': '用户管理',
                'menu_system_settings': '系统设置',
                'menu_backup': '数据备份',
                'menu_restore': '数据恢复',
                'menu_help': '使用帮助',
                'menu_about': '关于系统',
                'menu_logout': '退出登录',
                'menu_relogin': '重新登录',
                'logging_in': '登录中...',
                'relogin_success': '重新登录成功',
                'relogin_canceled': '重新登录已取消',
                'relogin_error': '重新登录失败',
                # 报表相关
                'report_type': '报表类型',
                'monthly_report': '月度报表',
                'tenant_detail_report': '租户明细报表',
                'payment_stat_report': '收费统计报表',
                'settlement_report': '结算报表',
                'query_conditions': '查询条件',
                'generate_report': '生成报表',
                'export_excel': '导出Excel',
                'export_pdf': '导出PDF',
                'report_result': '报表结果',
                'stat_chart': '统计图表',
                'chart_area': '图表区域',
                'generating_report_please_wait': '正在生成报表，请稍候...',
                'tab_reading_settings': '抄表设置',
                'tab_system_settings': '系统设置',
                'label_default_reading_day': '默认抄表日：',
                'label_reading_time_format': '抄表日期格式：',
                'label_max_usage_difference': '最大用量差值：',
                'label_auto_backup': '自动备份:',
                'label_backup_interval_days': '备份间隔（天）:',
                'label_language': '语言设置:',
                'stat_type': '统计方式',
                'checkbox_enable_auto_backup': '启用自动备份',
                'button_save': '保存',
                'button_cancel': '取消',
                'button_search': '搜索',
                'button_reset': '重置',
                'button_add': '添加',
                'button_edit': '编辑',
                'button_delete': '删除',
                'success_save_settings': '设置已保存！',
                'error_save_settings': '保存设置失败：',
                'permission_error': '只有管理员用户才能访问系统设置！',
                'success': '成功',
                'error': '错误',
                'menu_title': '功能菜单',
                'menu_group_dashboard': '仪表盘',
                'menu_group_data_management': '数据管理',
                'menu_group_system_config': '系统配置',
                'menu_overview': '概览',
                'menu_reading_entry': '抄表录入',
                'menu_charge_calculation': '费用计算',
                'menu_payment_entry': '收费录入',
                'menu_settlement_management': '费用结算',
                'menu_user_management': '用户管理',
                'menu_system_config': '系统设置',
                # 报表生成相关
                'monthly_water_electricity_report': '月度水电费报表',
                'report_month': '报表月份',
                'generate_time': '生成时间',
                'tenant_name': '租户名称',
                'total': '合计',
                'statistical_information': '统计信息',
                'total_tenants': '总租户数',
                'households': '户',
                'paid_count': '已缴户数',
                'unpaid_count': '未缴户数',
                'tenant_water_electricity_detail_report': '租户水电费明细报表',
                'payment_stat_report_title': '收费统计报表',
                'water_electricity_settlement_report': '水电费结算报表',
                'payment_statistics': '收费统计',
                'monthly_total_payment': '当月收费总金额',
                'payment_record_count': '收款笔数',
                'statistics_by': '按',
                'colon': ':',
                'statistical_item': '统计项',
                'amount_yuan': '金额(元)',
                'percentage': '百分比',
                'settlement_info': '结算信息',
                'no_settlement_this_month': '本月尚未结算',
                'suggested_settlement_amount': '建议结算金额',
                'login_window_title': '水电费抄收管理系统 - 登录',
                'login_system_title': '水电费抄收管理系统',
                'login_username': '用户名:',
                'login_password': '密码:',
                'login_remember_me': '记住我',
                'login_forgot_password': '忘记密码?',
                'login_login': '登录',
                'login_cancel': '取消',
                'login_warning_username': '请输入用户名',
                'login_warning_password': '请输入密码',
                'login_error_invalid': '用户名或密码错误，或账号已被禁用',
                'login_error_exception': '登录过程中发生错误：',
                'login_forgot_password_info': '请联系系统管理员重置密码',
                'server_online': '服务器在线',
                'data_synchronized': '数据已同步',
                'select_month': '选择月份',
                'refresh': '刷新',
                'monthly_income_trend': '月度收入趋势',
                'tenant_type_distribution': '租户类型分布',
                'revenue_composition': '收入来源构成',
                'total_tenants': '租户总数',
                'total_meters': '仪表总数',
                'monthly_revenue': '总收入',
                'unpaid_amount': '未收金额',
                'total_water_consumption': '总用水量',
                'total_electricity_consumption': '总用电量',
                'month': '月份',
                'revenue_amount': '收入金额（元）',
                'tenant_type': '租户类型',
                'households': '户',
                'percentage': '百分比',
                'water_fee': '水费',
                'electricity_fee': '电费',
                'total_income': '总收入',
                'water_meter': '水表',
                'electric_meter': '电表',
                'change': '变化',
                'update_time': '更新时间',
                'month_on_month': '环比',
                'year_on_year': '同比',
                'up': '上升',
                'down': '下降',
                'flat': '持平',
                'deactivated': '停用',
                'current_user': '当前用户',
                'current_date': '当前日期',
                'dashboard': '仪表盘',
                'data_management': '数据管理',
                'system_configuration': '系统配置',
                # 系统设置相关
                'system_backup_success': '数据库备份成功！\n备份文件路径：\n{0}',
                'system_backup_fail': '数据库备份失败！',
                'system_no_backup_dir': '没有找到备份目录！',
                'system_no_backup_files': '没有找到备份文件！',
                'system_select_backup_file': '请选择要恢复的备份文件！',
                'system_confirm_restore': '确定要从备份文件 {0} 恢复吗？\n恢复将覆盖当前数据库，此操作不可逆！',
                'system_restore_success': '数据库恢复成功！\n请重启系统以应用更改。',
                'system_restore_fail': '数据库恢复失败！',
                'system_admin_only': '只有管理员用户才能访问系统设置！',
                'system_about_title': '关于系统',
                'system_about_content': '{0}\n\n用于公司出租的办公室和门面的水电费抄表、计费、收费及结算管理',
                'version': '版本',
                'copyright': '© 2025 {0}. All rights reserved.',
                'technical_support': '技术支持',
                'system_init_admin_only': '只有管理员用户才能执行数据初始化操作！',
                'system_init_warning': '数据初始化将清空除用户表外的所有数据，此操作不可逆！\n\n请确认是否继续？\n\n建议在操作前先进行数据备份。',
                'system_backup_fail_continue': '数据备份失败，是否继续执行初始化？',
                'system_operation_result': '操作结果',
                'system_init_fail': '数据初始化失败：{0}',
                'system_confirm_exit': '确定要退出系统吗？',
                'system_load_price_fail': '加载租户价格数据失败：{0}',
                'system_select_price_item': '请先选择要删除的价格配置项',
                'system_confirm_delete': '确认删除',
                'system_delete_price_fail': '删除{0}价格配置时发生错误：{1}',
                'system_delete_price_success_single': '已成功删除{0}的价格配置',
                'system_delete_price_success_multi': '已成功删除{0}个价格配置',
                'system_delete_not_executed': '删除操作未执行',
                'system_delete_fail': '删除操作失败：{0}',
                'system_water_price_zero': '水价设置为0，确定要继续吗？',
                'system_water_price_too_high': '水价({0})过高，确定要继续吗？',
                'system_electricity_price_zero': '电价设置为0，确定要继续吗？',
                'system_electricity_price_too_high': '电价({0})过高，确定要继续吗？',
                'system_form_validation_fail': '表单验证失败',
                'system_add_price_success': '{0}价格配置新增成功！\n水价：{1}元/吨\n电价：{2}元/度',
                'system_save_price_fail': '保存租户价格配置失败：{0}',
                'system_edit_price_success': '{0}价格配置编辑成功！\n水价：{1}元/吨\n电价：{2}元/度',
                'export_charge_sheet': '导出收费表',
                'no_charge_data_to_export': '没有可导出的费用数据',
                'exporting_data_please_wait': '正在导出数据，请稍候...',
                'charge_sheet_exported_successfully': '收费表导出成功！',
                'export_failed': '导出失败',
                # 用户管理相关
                'user_management': '用户管理',
                'username': '用户名',
                'password': '密码',
                'role': '角色',
                'status': '状态',
                'create_time': '创建时间',
                'user_details': '用户明细',
                'admin': '管理员',
                'reader': '抄表员',
                'enabled': '启用',
                'disabled': '禁用',
                'loading': '加载中...',
                'load_users_fail': '加载用户列表失败：',
                'add_user': '添加用户',
                'please_fill_user_info': '请在右侧表单中填写用户信息，然后点击\'保存\'按钮',
                'please_select_user': '请先选择要删除的用户',
                'cannot_delete_last_admin': '不能删除最后一个管理员用户！',
                'confirm_delete_user': '确定要删除用户 \'{0}\' 吗？\n删除后将无法恢复。',
                'user_delete_success': '用户删除成功',
                'user_delete_fail': '用户删除失败',
                'user_update_success': '用户信息更新成功',
                'user_update_fail': '用户信息更新失败',
                'user_add_success': '用户添加成功',
                'user_add_fail': '用户添加失败',
                'username_exists': '用户名已存在，请选择其他用户名',
                'please_enter_username': '请输入用户名',
                'please_select_role': '请选择角色',
                'please_select_status': '请选择状态',
                'please_enter_password': '请输入密码',
                # 抄表管理相关
                'reading_management': '抄表管理',
                'month': '月份',
                'tenant': '租户',
                'meter': '水电表',
                'meter_no': '表编号',
                'meter_type': '表类型',
                'water_meter': '水表',
                'electric_meter': '电表',
                'previous_reading': '上次读数',
                'current_reading': '当前读数',
                'adjustment': '调整',
                'usage': '用量',
                'remark': '备注',
                'remark_length_limit': '备注不能超过200个字符',
                'reading_date': '抄表日期',
                'charging_time': '计费时间',
                'reader': '抄表人',
                'reading_details': '抄表明细',
                'make_hand_copy': '制作手抄单',
                'export_reading_form': '导出抄表单',
                'import_reading_form': '导入抄表单',
                'delete_reading': '删除记录',
                'select_all': '全选',
                'deselect_all': '取消全选',
                'total_records': '共 {0} 条记录',
                'serial': '序号',
                'tenant_name': '租户名称',
                'loading': '加载中...',
                'date_format_error': '月份格式不正确，应为YYYY-MM格式',
                'no_reading_selected': '请先选择要删除的抄表记录',
                'cannot_find_reading_info': '未找到所选水电表和月份的抄表记录',
                'cannot_delete_charged': '以下记录已计费，无法删除：',
                'operation_restriction': '操作限制',
                'confirm_delete': '确认删除',
                'reading_delete_success': '成功删除 {0} 条抄表记录',
                'reading_delete_fail': '抄表记录删除失败，可能是数据库操作错误',
                'delete_exception': '删除抄表记录时发生异常: {0}',
                'unknown_tenant': '未知租户',
                'failed_load_readings': '抄表记录列表加载失败: {0}',
                'previous_reading_cannot_be_empty': '上次读数不能为空',
                'current_reading_cannot_be_empty': '当前读数不能为空',
                'adjustment_cannot_be_empty': '调整值不能为空',
                'reading_date_cannot_be_empty': '抄表日期不能为空',
                'reading_saved_successfully': '抄表记录保存成功',
                'reading_save_failed': '抄表记录保存失败',
                # 租户管理相关
                'tenant_management': '租户管理',
                'tenant_name': '租户名称',
                'tenant_type': '租户类型',
                'office': '办公室',
                'storefront': '门面',
                'contact_person': '联系人',
                'phone': '联系电话',
                'email': '邮箱',
                'address': '地址',
                'deactivated': '停用',
                'yes': '是',
                'no': '否',
                'tenant_details': '租户详细信息',
                'add_tenant': '添加租户',
                'edit_tenant': '编辑租户',
                'delete_tenant': '删除租户',
                'refresh_list': '刷新列表',
                'export_tenant': '导出租户',
                'import_tenant': '导入租户',
                'tenant_list_load_fail': '租户列表加载失败: ',
                'please_select_tenant_edit': '请先选择要编辑的租户',
                'please_select_tenant_delete': '请先选择要删除的租户',
                'confirm_delete_tenant': '确定要删除以下租户信息吗？\n\n租户名称: {0}\n租户类型: {1}\n联系人: {2}\n联系电话: {3}\n\n删除后将无法恢复，是否继续？',
                'tenant_delete_success': '租户删除成功',
                'tenant_delete_fail': '租户删除失败，可能是数据库操作错误',
                'tenant_has_readings': '该租户已存在抄表记录，无法删除',
                'tenant_update_success': '租户信息更新成功',
                'tenant_update_fail': '租户信息更新失败，可能是数据库操作错误',
                'tenant_add_success': '租户添加成功',
                'tenant_add_fail': '租户添加失败，可能是数据库操作错误或已存在相同名称的租户',
                'please_enter_tenant_name': '请输入租户名称',
                'please_select_tenant_type': '请选择租户类型',
                'please_enter_contact_person': '请输入联系人',
                'please_enter_phone': '请输入联系电话',
                'export_tenant_success': '导出成功！\n文件路径：{0}',
                'export_tenant_fail': '导出租户信息失败: {0}',
                'import_tenant_fail': '导入租户信息失败: {0}',
                'file_format_error': '文件格式不正确，缺少以下必填列：{0}',
                'tenant_exists': '租户 \'{0}\' 已存在',
                'import_progress': '导入进度',
                'preparing_import': '准备导入...',
                'importing_row': '正在导入第 {0}/{1} 行...',
                'import_result': '导入结果',
                'import_completed': '导入完成！\n\n总计: {0} 行\n成功: {1} 行\n失败: {2} 行\n',
                'failed_reasons': '失败原因:',
                'more_failed_reasons': '... 还有 {0} 条失败原因未显示\n',
                'saving_tenant': '保存租户信息中...',
                'cannot_get_tenant_id': '未能获取租户ID',
                'cannot_find_tenant_info': '未能找到所选租户的详细信息',
                'save_tenant_exception': '保存租户信息时发生异常: {0}',
                'tenant_id': '租户ID',
                'create_time': '创建时间',
                'tenant_information': '租户信息',
                'select_tenant_excel_file': '选择要导入的租户Excel文件',
                'fail': '失败',
                'success': '成功',
                # 水电表管理相关
                'meter_management': '水电表管理',
                'meter_no': '表编号',
                'water_meter': '水',
                'electric_meter': '电',
                'meter_type': '表类型',
                'tenant': '所属租户',
                'location': '安装位置',
                'initial_reading': '初始读数',
                'status': '状态',
                'normal': '正常',
                'damaged': '损坏',
                'replaced': '更换',
                'meter_details': '水电表明细',
                'add_meter': '添加水电表',
                'edit_meter': '编辑水电表',
                'delete_meter': '删除水电表',
                'refresh_list': '刷新列表',
                'export_meter': '导出水电表',
                'import_meter': '导入水电表',
                'load_tenant_list_exception': '加载租户列表时发生异常：{0}',
                'search_meter_exception': '搜索水电表时发生异常：{0}',
                'failed_to_get_meter_id': '未能获取水电表ID',
                'data_synchronizing': '数据正在同步中...',
                'failed_to_fill_form': '填充表单时发生异常：{0}',
                'please_select_meter_edit': '请先选择要编辑的水电表',
                'please_select_meter_delete': '请先选择要删除的水电表',
                'failed_to_find_meter': '未找到要删除的水电表信息',
                'confirm_delete_meter': '确定要删除水电表 \'{0}\' 吗？\n删除后将无法恢复。',
                'meter_delete_success': '水电表 \'{0}\' 删除成功',
                'meter_delete_fail': '水电表删除失败，请检查该水电表是否已关联抄表记录或费用记录',
                'delete_meter_exception': '删除水电表时发生异常：{0}',
                'load_meter_list_exception': '加载水电表列表时发生异常：{0}',
                'list_refreshed': '列表已刷新',
                'search_completed': '搜索完成，找到 {0} 条记录',
                'temporary_message': '提示',
                'please_enter_meter_no': '请输入表编号',
                'please_select_meter_type': '请选择表类型',
                'please_select_tenant': '请选择所属租户',
                'please_enter_location': '请输入安装位置',
                'initial_reading_must_be_number': '初始读数必须是数字',
                'please_select_status': '请选择状态',
                'please_select_valid_tenant': '请选择有效的租户',
                'meter_no_exists': '表编号 \'{0}\' 已存在，请使用其他表编号',
                'meter_update_success': '水电表 \'{0}\' 更新成功',
                'meter_update_fail': '水电表信息更新失败',
                'meter_add_success': '水电表 \'{0}\' 添加成功',
                'meter_add_fail': '水电表添加失败',
                'save_meter_exception': '保存水电表信息时发生异常：{0}',
                'meter_information': '水电表信息',
                'meter_id': '水电表ID',
                'create_time': '创建时间',
                'export_meter_success': '导出成功！\n文件路径：{0}',
                'export_meter_fail': '导出水电表信息失败: {0}',
                'import_meter_fail': '导入水电表信息失败: {0}',
                'select_meter_excel_file': '选择要导入的水电表Excel文件',
                'file_format_error': '文件格式不正确，缺少以下必填列：{0}',
                'meter_no_cannot_be_empty': '表编号不能为空',
                'meter_type_must_be_water_or_electric': '表类型必须是\'水\'或\'电\'',
                'tenant_cannot_be_empty': '所属租户不能为空',
                'tenant_not_exist': '租户 \'{0}\' 不存在，请先添加该租户',
                'location_cannot_be_empty': '安装位置不能为空',
                'initial_reading_must_be_a_number': '初始读数必须是数字',
                'status_must_be_normal_damaged_or_replaced': '状态必须是\'正常\'、\'损坏\'或\'更换\'',
                'import_progress': '导入进度',
                'preparing_import': '准备导入...',
                'importing_row': '正在导入第 {0}/{1} 行...',
                'import_result': '导入结果',
                'import_completed': '导入完成！\n\n总计: {0} 行\n成功: {1} 行\n失败: {2} 行\n',
                'failed_reasons': '失败原因:',
                'more_failed_reasons': '... 还有 {0} 条失败原因未显示\n',
                # 按钮文本
                'button_ok': '确定',
                'button_cancel': '取消',
                'button_yes': '是',
                'button_no': '否',
                # 提示类型
                'info': '提示',
                'warning': '警告',
                'error': '错误',
                # 统计相关
                'usage_total': '用量总数',
                'adjustment_total': '调整总数',
                'avg_usage': '平均用量',
                # 价格管理相关
                'water': '水',
                'electricity': '电',
                'resource_type': '资源类型',
                'tenant_type': '租户类型',
                'price': '价格',
                'office': '办公室',
                'storefront': '门面',
                'all': '全部',
                'effective_start_date': '生效开始日期',
                'effective_end_date': '生效结束日期',
                'price_details': '价格明细',
                'date_format': '格式',
                'date_format_yyyy_mm_dd': '(格式: YYYY-MM-DD)',
                'leave_empty_for_permanent': '留空表示长期有效',
                'price_list_refresh_fail': '价格列表刷新失败',
                'cannot_find_price_details': '未能找到所选价格的详细信息',
                'please_select_price_edit': '请先选择要编辑的价格',
                'entered_edit_mode': '已进入编辑模式，正在编辑',
                'price_record': '价格记录',
                'please_modify_form_and_save': '请修改右侧表单并点击保存按钮',
                'please_select_price_delete': '请先选择要删除的价格',
                'yuan': '元',
                'ton': '吨',
                'kwh': '度',
                'permanent': '长期有效',
                'delete_irreversible': '删除后将无法恢复，',
                'continue': '是否继续？',
                'delete_success': '删除成功',
                'database_error': '，可能是数据库操作错误',
                'delete_price_exception': '删除价格时发生异常',
                'please_select_resource_type': '请选择资源类型',
                'please_select_tenant_type': '请选择租户类型',
                'please_enter_price': '请输入单价',
                'price_cannot_be_negative': '单价不能为负数',
                'price_cannot_be_zero': '单价不能为零',
                'price_must_be_valid_number': '单价必须是有效的数字',
                'please_enter_effective_start_date': '请输入生效开始日期',
                'effective_start_date_format_error': '生效开始日期格式不正确',
                'correct_format': '正确格式',
                'effective_end_date_format_error': '生效结束日期格式不正确',
                'start_date_cannot_be_later_than_end_date': '生效开始日期不能晚于生效结束日期',
                'update_success': '更新成功',
                'update_fail': '更新失败',
                'add_success': '添加成功',
                'add_fail': '添加失败',
                'database_error_or_duplicate': '，可能是数据库操作错误或已存在相同条件的价格记录',
                'save_price_exception': '保存价格信息时发生异常',
                # 费用管理相关
                'calculate_charges': '计算费用',
                'delete_records': '删除记录',
                'unpaid': '未缴',
                'paid': '已缴',
                'partially_paid': '部分缴纳',
                'water_usage': '用水量',
                'water_price': '水价',
                'electricity_usage': '用电量',
                'electricity_price': '电价',
                'water_charge': '水费',
                'electricity_charge': '电费',
                'total_charge': '总费用',
                'paid_amount': '已收费用',
                'due_amount': '应收费用',
                'charge_details': '费用明细',
                'total': '共',
                'records': '条记录',
                'total_water_charge': '总水费金额',
                'total_electricity_charge': '总电费金额',
                'total_paid_amount': '已收总费用金额',
                'total_due_amount': '应收总费用金额',
                'unknown_tenant': '未知租户',
                'charge_month': '费用月份',
                'water_charge_details': '水费明细',
                'electricity_charge_details': '电费明细',
                'usage': '用量',
                'units': '单位',
                'unit': '单位',
                'amount': '金额',
                'charge_status': '费用状态',
                'loading': '加载中',
                'please_wait_getting_charge_details': '请稍候，正在获取费用明细',
                'please_select_records_to_delete': '请先选择要删除的记录',
                'record': '记录',
                'status_is_paid_cannot_delete': '状态为已缴，无法删除',
                'status_is_partially_paid_cannot_delete': '状态为部分缴纳，无法删除',
                'related_payment_records': '关联的收费记录',
                'has_related_payment_records_cannot_delete': '存在关联的收费记录，不允许删除',
                'charge_record_status_is_paid_cannot_delete': '该费用记录状态为已缴，无法删除',
                'charge_record_status_is_partially_paid_cannot_delete': '该费用记录状态为部分缴纳，无法删除',
                'record_has_related_payment_records_not_allowed_delete': '此记录存在关联的收费记录，不允许删除',
                'operation_tip': '操作提示',
                'confirm_delete_selected_records': '确定要删除选中的',
                'this_operation_cannot_be_undone': '此操作不可恢复！',
                'delete_result': '删除结果',
                'delete_completed': '删除完成',
                'successfully_deleted': '成功删除',
                'charge_calculation_completed': '费用计算完成',
                'new_added': '新增',
                'updated': '更新',
                'households': '户',
                'calculation_result': '计算结果',
                # 收费管理相关
                'charge_information': '收费信息',
                'charge_query': '费用查询',
                'payment_query': '收费查询',
                'query_arrears': '欠费查询',
                'delete_payment': '删除收费',
                'generate_payment_receipt': '收费凭证',
                'payment_date': '缴费日期',
                'settlement_date': '结算时间',
                'payment_method': '缴费方式',
                'cash': '现金',
                'bank_transfer': '银行转账',
                'wechat': '微信',
                'alipay': '支付宝',
                'payer': '收费人',
                'failed_to_load_tenant_data': '加载租户数据失败',
                'failed_to_load_form_tenant_data': '加载表单租户数据失败',
                'invalid_payment_record_id': '无效的收费记录ID',
                'please_select_payment_to_delete': '请先选择要删除的收费记录',
                'operation_restriction': '操作限制',
                'payment_record_settled_cannot_delete': '该收费记录已结算，无法删除',
                'confirm_delete_this_payment_record': '确定要删除这条收费记录',
                'payment_record_deleted_successfully_status_updated': '收费记录删除成功，并已同步更新费用记录状态',
                'failed_to_delete_payment_record': '收费记录删除失败',
                'please_select_tenant': '请选择租户',
                'please_select_charge_month': '请选择费用月份',
                'please_enter_amount': '请输入收费金额',
                'amount_must_be_number': '收费金额必须是数字',
                'amount_must_be_greater_than_zero': '收费金额必须大于0',
                'please_enter_payment_date': '请输入收费日期',
                'please_select_payment_method': '请选择支付方式',
                'please_enter_payer': '请输入收款人',
                'please_select_valid_tenant': '请选择有效的租户',
                'tenant_no_charge_for_month': '该租户在该月份没有费用记录',
                'payment_record_updated_successfully': '收费记录更新成功',
                'failed_to_update_payment_record': '收费记录更新失败',
                'payment_record_added_successfully': '收费记录添加成功',
                'failed_to_add_payment_record': '收费记录添加失败',
                # 主窗口相关
                'menu_file': '文件',
                'menu_base_info': '基础信息',
                'menu_meter_reading': '抄表录入',
                'menu_charge_calculation': '费用计算',
                'menu_payment_entry': '收费录入',
                'menu_settlement': '费用结算',
                'menu_monthly_report': '报表中心',
                'menu_data_backup': '数据备份',
                'menu_data_restore': '数据恢复',
                'menu_data_initialization': '数据初始化',
                'welcome': '欢迎',
                'data_restore': '数据恢复',
                'select_backup_file': '选择备份文件：',
                'backup_date': '备份日期',
                'form_title_tenant_management': '租户管理',
                'form_title_meter_management': '水电表管理',
                'form_title_price_management': '价格管理',
                'form_title_reading_entry': '抄表录入',
                'form_title_charge_calculation': '费用计算',
                'form_title_payment_entry': '收费录入',
                'form_title_settlement_management': '费用结算',
                'form_title_report_management': '报表中心',
                'form_title_user_management': '用户管理',
                'form_title_system_settings': '系统设置',
                'notes': '备注',
                'payment_receipt': '收费凭证',
                'arrears_query': '欠费查询',
                'total_arrears': '总计欠费',
                'arrears_count': '欠费租户数',
                'close': '关闭',
                'format_error': '格式错误',
                'month_format_yyyy_mm': '月份格式不正确，应为YYYY-MM格式',
                'auto_match_charge_fail': '自动匹配费用记录失败',
                'calculate_total_paid_fail': '计算总缴费金额失败',
                'update_charge_status_fail': '更新费用状态失败',
                'load_charge_months_fail': '加载费用月份失败',
                'deleting': '删除中',
                'updating': '更新中',
                'querying': '查询中',
                'filename': '文件名',
                'unknown_date': '未知日期',
                'button_restore': '恢复',
                'unknown_tenant': '未知租户',
                'menu_user_management': '用户管理',
                'total_arrears': '总欠费金额',
                'select_all': '全选',
                'import_to_payment': '导入到收费',
                'please_select_records_to_import': '请先选择要导入的记录',
                'payment_records': '欠费记录数',
                'records': '条记录',
                'refreshed': '已刷新',
                'total_loaded': '共加载到',
                'failed_to_refresh': '刷新',
                'failed_to_update_stats': '更新统计标签失败',
                # 结算管理相关
                'settlement_management': '结算管理',
                'settle_month': '结算月份',
                'search': '查询',
                'reset': '重置',
                'add_settlement': '新增结算',
                'edit_settlement': '编辑结算',
                'delete_settlement': '删除结算',
                'generate_settlement_report': '生成结算报表',
                'refresh_list': '刷新列表',
                'serial': '序号',
                'settle_date': '结算日期',
                'total_amount': '结算金额',
                'cashier': '出纳',
                'notes': '备注',
                'settlement_details': '结算明细',
                'calculate_monthly_received': '计算当月已收金额',
                'save': '保存',
                'cancel': '取消',
                'operation_guide': '操作指引',
                'guide_step_1': '1. 输入结算月份',
                'guide_step_2': '2. 点击"计算当月已收金额"按钮自动计算金额',
                'guide_step_3': '3. 补充结算日期、出纳等信息',
                'guide_step_4': '4. 点击"保存"按钮完成添加',
                'edit_mode': '已进入编辑模式',
                'editing': '正在编辑',
                'please_select_settlement_to_edit': '请先选择要编辑的结算记录',
                'data_expired_please_refresh': '无法找到该结算记录，可能数据已过期，请刷新列表后重试',
                'settlement_id_invalid': '结算记录ID无效，请刷新列表后重试',
                'please_select_settlement_to_delete': '请先选择要删除的结算记录',
                'confirm_delete_settlement': '确认删除',
                'delete_irreversible': '删除后将无法恢复，是否继续？',
                'settlement_deleted_successfully': '结算记录删除成功',
                'settlement_delete_failed': '结算记录删除失败',
                'please_enter_settlement_month': '请输入结算月份',
                'settle_month_format_error': '结算月份格式不正确，应为YYYY-MM格式（如2025-12）',
                'monthly_received_calculation_result': '{0}月份已收金额计算结果',
                'total_received_amount': '总已收金额',
                'payment_count': '收款笔数',
                'payment_method_distribution': '支付方式分布',
                'no_data': '无数据',
                'calculation_result_filled': '计算结果已自动填充到结算金额字段',
                'manual_adjustment_allowed': '您可以根据需要手动调整金额',
                'settlement_amount_cannot_be_negative': '结算金额不能为负数',
                'settlement_amount_must_be_valid_number': '结算金额必须是有效的数字',
                'please_enter_settle_date': '请输入结算日期',
                'settle_date_format_error': '结算日期格式不正确，应为YYYY-MM-DD格式（如2025-12-31）',
                'settle_date_cannot_be_before_month_start': '结算日期不能早于{0}-01',
                'settle_date_cannot_be_after_current_date': '结算日期不能晚于当前日期',
                'please_enter_cashier_name': '请输入出纳姓名',
                'cashier_name_too_long': '出纳姓名不能超过50个字符',
                'notes_too_long': '备注不能超过200个字符',
                'settlement_month_already_exists': '{0}月份已经有结算记录，无法修改到该月份',
                'settlement_update_success': '结算记录更新成功\n已更新{0}月份的结算记录',
                'settlement_add_success': '结算记录添加成功\n已添加{0}月份的结算记录',
                'database_operation_failed': '数据库操作失败，无法{0}结算记录',
                'confirm_generate_report': '是否要生成{0}月份的结算报表？',
                'settlement_report_success': '结算报表已成功导出到\n{0}',
                'settlement_report_failed': '生成结算报表失败：{0}',
                'generate_time': '生成时间',
                'settlement_summary': '{0}结算汇总',
                'monthly_settlement_report': '{0}月份结算报表',
                'settlement_details_sheet': '{0}结算明细',
                'payment_details_sheet': '{0}缴费明细',
                'item': '项目',
                'amount_quantity': '金额/数量',
                'description': '说明',
                'total_charge_amount': '总费用金额',
                'paid_amount': '已收金额',
                'arrears_amount': '欠费金额',
                'paid_households': '已缴户数',
                'total_households': '总租户数',
                'payment_rate': '缴费率',
                'tenant_name': '租户名称',
                'receipt_no': '收据号',
                'collector': '收费人',
                'unknown_payer': '未知收费人',
                # 帮助文档常见问题
                'technical_support': '技术支持',
                'contact_info': '联系方式',
                'official_website': '官方网站',
                'online_docs': '在线文档',
                'tenant_management_desc': '租户管理模块用于添加、编辑和删除租户信息，包括租户名称、联系方式、租赁面积等。您可以通过左侧菜单的"租户管理"菜单项进入该模块。',
                'meter_management_desc': '水电表管理模块用于添加、编辑和删除水电表信息，包括水表编号、电表编号、租户信息等。您可以通过左侧菜单的"水电表管理"菜单项进入该模块。',
                'reading_management_desc': '抄表管理模块用于录入和查询抄表数据，包括抄表日期、水表读数、电表读数等。您可以通过左侧菜单的"抄表管理"菜单项进入该模块。',
                'charge_management_desc': '计费管理模块用于计算和管理租户的水电费用，系统会根据抄表数据和价格设置自动计算费用。您可以通过左侧菜单的"计费管理"菜单项进入该模块。',
                'payment_management_desc': '收费管理模块用于录入和查询收费数据，包括收费日期、收费金额、收费方式等。您可以通过左侧菜单的"收费管理"菜单项进入该模块。',
                'report_management_desc': '报表管理模块用于生成各种报表，包括月度报表、租户明细报表、收费统计报表等。您可以通过左侧菜单的"报表管理"菜单项进入该模块。',
                # 常见问题FAQ
                'faq_how_to_view_history_charges': '如何查看历史收费记录？',
                'faq_how_to_add_meter': '如何添加新的水电表？',
                'faq_how_to_modify_tenant_info': '如何修改租户信息？',
                'faq_how_to_generate_tenant_report': '如何生成租户明细报表？',
                'faq_how_to_set_system_params': '如何设置系统参数？',
                'faq_answer_view_history_charges': '要查看历史收费记录，您可以通过左侧菜单进入费用管理模块。在该模块中，您可以选择租户和时间范围，然后查看该租户的历史收费记录。',
                'faq_answer_add_meter': '要添加新的水电表，您可以通过左侧菜单进入水电表管理模块。在该模块中，您可以添加新的水电表信息，包括表编号、类型、所属租户等。',
                'faq_answer_modify_tenant_info': '要修改租户信息，您可以通过左侧菜单进入租户管理模块。在该模块中，您可以找到要修改的租户，然后点击编辑按钮修改租户信息。',
                'faq_answer_generate_tenant_report': '要生成租户明细报表，您可以通过左侧菜单进入报表中心模块。在该模块中，您可以选择"租户明细报表"类型，然后选择租户和时间范围，点击"生成报表"按钮即可生成。',
                'faq_answer_set_system_params': '要设置系统参数，您可以通过左侧菜单进入系统设置模块。在该模块中，您可以设置各种系统参数，如抄表日期、价格设置等。',
                # 报表相关
                'monthly_water_electricity_report': '月度水电费报表',
                'report_month': '报表月份',
                'by_tenant': '按租户',
                'by_type': '按类型',
                'unknown_type': '未知类型',
                'unknown_tenant': '未知租户',
                'tenant_water_electricity_detail_report': '租户水电费明细报表',
                'payment_stat_report_title': '收费统计报表',
                'water_electricity_settlement_report': '水电费结算报表',
                'payment_statistics': '收费统计',
                'monthly_total_payment': '当月收费总金额',
                'payment_record_count': '收款笔数',
                'statistics_by': '按',
                'statistical_item': '统计项',
                'amount_yuan': '金额(元)',
                'settlement_info': '结算信息',
                'settlement_date': '结算时间',
                'settlement_amount': '结算金额',
                'cashier': '出纳',
                'notes': '备注',
                'none': '无',
                'percentage': '百分比',
                'no_settlement_this_month': '本月尚未结算',
                'suggested_settlement_amount': '建议结算金额',
                # 导出相关
                'export_excel_report': '导出Excel报表',
                'excel_report_successfully_exported_to': 'Excel报表已成功导出到',
                'failed_to_export_excel_report': '导出Excel报表失败',
                # 图表相关
                'chart_area': '图表区域',
                'generating_report_please_wait': '正在生成报表，请稍候...',
                # 数据库和状态相关
                'database': '数据库',
                'data_status': '数据状态',
                'normal': '正常',
                # 软件信息相关
                'software_info': '软件信息',
                'software_brand': '软件品牌',
                'software_name': '软件名称',
                'software_version': '软件版本号',
                'developer': '开发者',
                'development_date': '开发日期',
            },
            'en_US': {
                'window_title': 'Water and Electricity Management System',
                'menu_dashboard': 'Dashboard',
                'menu_tenant': 'Tenant Management',
                'menu_meter': 'Meter Management',
                'menu_reading': 'Reading Management',
                'menu_charge': 'Charging Management',
                'menu_payment': 'Payment Management',
                'menu_settlement': 'Settlement Management',
                'menu_price': 'Price Management',
                'menu_report': 'Report Management',
                'menu_user': 'User Management',
                'menu_system_settings': 'System Settings',
                'menu_backup': 'Data Backup',
                'menu_restore': 'Data Restore',
                'menu_help': 'Help',
                'menu_about': 'About',
                'menu_logout': 'Logout',
                'menu_relogin': 'Relogin',
                'logging_in': 'Logging in...',
                'relogin_success': 'Relogin successful',
                'relogin_canceled': 'Relogin canceled',
                'relogin_error': 'Relogin failed',
                'report_type': 'Report Type',
                'monthly_report': 'Monthly Report',
                'tenant_detail_report': 'Tenant Detail Report',
                'payment_stat_report': 'Payment Stat Report',
                'settlement_report': 'Settlement Report',
                'query_conditions': 'Query Conditions',
                'generate_report': 'Generate Report',
                'export_excel': 'Export Excel',
                'export_pdf': 'Export PDF',
                'report_result': 'Report Result',
                'stat_chart': 'Statistical Chart',
                'chart_area': 'Chart Area',
                'generating_report_please_wait': 'Generating report, please wait...',
                'tab_reading_settings': 'Reading Settings',
                'tab_system_settings': 'System Settings',
                'label_default_reading_day': 'Default Reading Day:',
                'label_reading_time_format': 'Reading Time Format:',
                'label_max_usage_difference': 'Max Usage Difference:',
                'label_auto_backup': 'Auto Backup:',
                'label_backup_interval_days': 'Backup Interval (Days):',
                'label_language': 'Language:',
                'stat_type': 'Stat Type',
                'checkbox_enable_auto_backup': 'Enable Auto Backup',
                'button_save': 'Save',
                'button_cancel': 'Cancel',
                'button_search': 'Search',
                'button_reset': 'Reset',
                'button_add': 'Add',
                'button_edit': 'Edit',
                'button_delete': 'Delete',
                'success_save_settings': 'Settings saved successfully!',
                'error_save_settings': 'Failed to save settings:',
                'permission_error': 'Only admin users can access system settings!',
                'success': 'Success',
                'error': 'Error',
                'menu_title': 'Function Menu',
                'menu_group_dashboard': 'Dashboard',
                'menu_group_data_management': 'Data Management',
                'menu_group_system_config': 'System Config',
                'menu_overview': 'Overview',
                'menu_reading_entry': 'Reading Entry',
                'menu_charge_calculation': 'Charge Calculation',
                'menu_payment_entry': 'Payment Entry',
                'menu_settlement_management': 'Settlement Management',
                'menu_user_management': 'User Management',
                'menu_system_config': 'System Settings',
                'monthly_water_electricity_report': 'Monthly Water and Electricity Report',
                'report_month': 'Report Month',
                'generate_time': 'Generate Time',
                'tenant_name': 'Tenant Name',
                'total': 'Total',
                'statistical_information': 'Statistical Information',
                'total_tenants': 'Total Tenants',
                'households': 'Households',
                'paid_count': 'Paid Households',
                'unpaid_count': 'Unpaid Households',
                'tenant_water_electricity_detail_report': 'Tenant Water and Electricity Detail Report',
                'payment_stat_report_title': 'Payment Stat Report',
                'water_electricity_settlement_report': 'Water and Electricity Settlement Report',
                'payment_statistics': 'Payment Statistics',
                'export_charge_sheet': 'Export Charge Sheet',
                'no_charge_data_to_export': 'No charge data to export',
                'exporting_data_please_wait': 'Exporting data, please wait...',
                'charge_sheet_exported_successfully': 'Charge sheet exported successfully!',
                'export_failed': 'Export failed',
                'monthly_total_payment': 'Monthly Total Payment',
                'payment_record_count': 'Payment Record Count',
                'statistics_by': 'By',
                'colon': ':',
                'statistical_item': 'Statistical Item',
                # 统计相关
                'usage_total': 'Total Usage',
                'adjustment_total': 'Total Adjustment',
                'avg_usage': 'Average Usage',
                'amount_yuan': 'Amount (Yuan)',
                'settlement_info': 'Settlement Information',
                'settlement_date': 'Settlement Date',
                'settlement_amount': 'Settlement Amount',
                'cashier': 'Cashier',
                'notes': 'Notes',
                'none': 'None',
                'percentage': 'Percentage',
                'no_settlement_this_month': 'No settlement this month',
                'suggested_settlement_amount': 'Suggested Settlement Amount',
                'login_window_title': 'Water and Electricity Management System - Login',
                'login_system_title': 'Water and Electricity Management System',
                'login_username': 'Username:',
                'login_password': 'Password:',
                'login_remember_me': 'Remember Me',
                'login_forgot_password': 'Forgot Password?',
                'login_login': 'Login',
                'login_cancel': 'Cancel',
                'login_warning_username': 'Please enter username',
                'login_warning_password': 'Please enter password',
                'login_error_invalid': 'Invalid username or password, or account disabled',
                'login_error_exception': 'Error during login:',
                'login_forgot_password_info': 'Please contact system administrator to reset password',
                'server_online': 'Server Online',
                'data_synchronized': 'Data Synchronized',
                'select_month': 'Select Month',
                'refresh': 'Refresh',
                'monthly_income_trend': 'Monthly Income Trend',
                'tenant_type_distribution': 'Tenant Type Distribution',
                'revenue_composition': 'Revenue Composition',
                'total_tenants': 'Total Tenants',
                'total_meters': 'Total Meters',
                'monthly_revenue': 'Monthly Revenue',
                'unpaid_amount': 'Unpaid Amount',
                'total_water_consumption': 'Total Water Consumption',
                'total_electricity_consumption': 'Total Electricity Consumption',
                'month': 'Month',
                'revenue_amount': 'Revenue Amount (Yuan)',
                'tenant_type': 'Tenant Type',
                'households': 'Households',
                'percentage': 'Percentage',
                'water_fee': 'Water Fee',
                'electricity_fee': 'Electricity Fee',
                'total_income': 'Total Income',
                'water_meter': 'Water Meter',
                'electric_meter': 'Electric Meter',
                'change': 'Change',
                'update_time': 'Update Time',
                'month_on_month': 'Month-on-Month',
                'year_on_year': 'Year-on-Year',
                'up': 'Up',
                'down': 'Down',
                'flat': 'Flat',
                'deactivated': 'Deactivated',
                'current_user': 'Current User',
                'current_date': 'Current Date',
                'dashboard': 'Dashboard',
                'data_management': 'Data Management',
                'system_configuration': 'System Configuration',
                'system_backup_success': 'Database backup successful!\nBackup file path:\n{0}',
                'system_backup_fail': 'Database backup failed!',
                'system_no_backup_dir': 'No backup directory found!',
                'system_no_backup_files': 'No backup files found!',
                'system_select_backup_file': 'Please select a backup file to restore!',
                'system_confirm_restore': 'Are you sure to restore from backup file {0}?\nRestoration will overwrite current database, this operation is irreversible!',
                'system_restore_success': 'Database restore successful!\nPlease restart the system to apply changes.',
                'system_restore_fail': 'Database restore failed!',
                'system_admin_only': 'Only admin users can access system settings!',
                'system_about_title': 'About System',
                'system_about_content': '{0}\n\nUsed for water and electricity meter reading, billing, payment and settlement management for company rented offices and storefronts',
                'version': 'Version',
                'copyright': '© 2025 {0}. All rights reserved.',
                'technical_support': 'Technical Support',
                'system_init_admin_only': 'Only admin users can perform data initialization operations!',
                'system_init_warning': 'Data initialization will clear all data except user table, this operation is irreversible!\n\nAre you sure to continue?\n\nIt is recommended to backup data before operation.',
                'system_backup_fail_continue': 'Data backup failed, continue initialization?',
                'system_operation_result': 'Operation Result',
                'system_init_fail': 'Data initialization failed: {0}',
                'system_confirm_exit': 'Are you sure to exit the system?',
                'system_load_price_fail': 'Failed to load tenant price data: {0}',
                'system_select_price_item': 'Please select the price configuration item to delete',
                'system_confirm_delete': 'Confirm Delete',
                'system_delete_price_fail': 'Error deleting {0} price configuration: {1}',
                'system_delete_price_success_single': 'Successfully deleted {0} price configuration',
                'system_delete_price_success_multi': 'Successfully deleted {0} price configurations',
                'system_delete_not_executed': 'Delete operation not executed',
                'system_delete_fail': 'Delete operation failed: {0}',
                'system_water_price_zero': 'Water price is set to 0, continue?',
                'system_water_price_too_high': 'Water price({0}) is too high, continue?',
                'system_electricity_price_zero': 'Electricity price is set to 0, continue?',
                'system_electricity_price_too_high': 'Electricity price({0}) is too high, continue?',
                'system_form_validation_fail': 'Form validation failed',
                'system_add_price_success': '{0} price configuration added successfully!\nWater Price: {1} Yuan/ton\nElectricity Price: {2} Yuan/kwh',
                'system_save_price_fail': 'Failed to save tenant price configuration: {0}',
                'system_edit_price_success': '{0} price configuration edited successfully!\nWater Price: {1} Yuan/ton\nElectricity Price: {2} Yuan/kwh',
                'user_management': 'User Management',
                'username': 'Username',
                'password': 'Password',
                'role': 'Role',
                'status': 'Status',
                'create_time': 'Create Time',
                'user_details': 'User Details',
                'admin': 'Admin',
                'reader': 'Reader',
                'enabled': 'Enabled',
                'disabled': 'Disabled',
                'loading': 'Loading...',
                'load_users_fail': 'Failed to load user list:',
                'add_user': 'Add User',
                'please_fill_user_info': 'Please fill in user information in the form on the right, then click \'Save\' button',
                'please_select_user': 'Please select a user to delete',
                'cannot_delete_last_admin': 'Cannot delete the last admin user!',
                'confirm_delete_user': 'Are you sure to delete user \'{0}\'?\nCannot recover after deletion.',
                'user_delete_success': 'User deleted successfully',
                'user_delete_fail': 'Failed to delete user',
                'user_update_success': 'User information updated successfully',
                'user_update_fail': 'Failed to update user information',
                'user_add_success': 'User added successfully',
                'user_add_fail': 'Failed to add user',
                'username_exists': 'Username already exists, please choose another username',
                'please_enter_username': 'Please enter username',
                'please_select_role': 'Please select role',
                'please_select_status': 'Please select status',
                'please_enter_password': 'Please enter password',
                'reading_management': 'Reading Management',
                'month': 'Month',
                'tenant': 'Tenant',
                'meter': 'Meter',
                'meter_no': 'Meter No',
                'meter_type': 'Meter Type',
                'water_meter': 'Water Meter',
                'electric_meter': 'Electric Meter',
                'previous_reading': 'Previous Reading',
                'current_reading': 'Current Reading',
                'adjustment': 'Adjustment',
                'usage': 'Usage',
                'reading_date': 'Reading Date',
                'charging_time': 'Charging Time',
                'reader': 'Reader',
                'reading_details': 'Reading Details',
                'make_hand_copy': 'Make Hand Copy',
                'export_reading_form': 'Export Reading Form',
                'import_reading_form': 'Import Reading Form',
                'delete_reading': 'Delete Records',
                'select_all': 'Select All',
                'deselect_all': 'Deselect All',
                'total_records': 'Total {0} records',
                'serial': 'Serial',
                'tenant_name': 'Tenant Name',
                'loading': 'Loading...',
                'date_format_error': 'Invalid month format, should be YYYY-MM format',
                'no_reading_selected': 'Please select reading records to delete',
                'cannot_find_reading_info': 'Cannot find reading records for selected meter and month',
                'cannot_delete_charged': 'The following records have been charged, cannot delete:',
                'operation_restriction': 'Operation Restriction',
                'confirm_delete': 'Confirm Delete',
                'reading_delete_success': 'Successfully deleted {0} reading records',
                'reading_delete_fail': 'Failed to delete reading records, maybe database operation error',
                'delete_exception': 'Exception occurred when deleting reading records: {0}',
                'unknown_tenant': 'Unknown Tenant',
                'failed_load_readings': 'Failed to load reading records: {0}',
                'previous_reading_cannot_be_empty': 'Previous reading cannot be empty',
                'current_reading_cannot_be_empty': 'Current reading cannot be empty',
                'adjustment_cannot_be_empty': 'Adjustment value cannot be empty',
                'reading_date_cannot_be_empty': 'Reading date cannot be empty',
                'reading_saved_successfully': 'Reading records saved successfully',
                'reading_save_failed': 'Failed to save reading records',
                'tenant_management': 'Tenant Management',
                'tenant_name': 'Tenant Name',
                'tenant_type': 'Tenant Type',
                'office': 'Office',
                'storefront': 'Storefront',
                'contact_person': 'Contact Person',
                'phone': 'Phone',
                'email': 'Email',
                'address': 'Address',
                'deactivated': 'Deactivated',
                'yes': 'Yes',
                'no': 'No',
                'tenant_details': 'Tenant Details',
                'add_tenant': 'Add Tenant',
                'edit_tenant': 'Edit Tenant',
                'delete_tenant': 'Delete Tenant',
                'refresh_list': 'Refresh List',
                'export_tenant': 'Export Tenant',
                'import_tenant': 'Import Tenant',
                'tenant_list_load_fail': 'Failed to load tenant list: ',
                'please_select_tenant_edit': 'Please select a tenant to edit',
                'please_select_tenant_delete': 'Please select a tenant to delete',
                'confirm_delete_tenant': 'Are you sure to delete the following tenant information?\n\nTenant Name: {0}\nTenant Type: {1}\nContact Person: {2}\nPhone: {3}\n\nCannot recover after deletion, continue?',
                'tenant_delete_success': 'Tenant deleted successfully',
                'tenant_delete_fail': 'Failed to delete tenant, maybe database operation error',
                'tenant_has_readings': 'This tenant has reading records, cannot delete',
                'tenant_update_success': 'Tenant information updated successfully',
                'tenant_update_fail': 'Failed to update tenant information, maybe database operation error',
                'tenant_add_success': 'Tenant added successfully',
                'tenant_add_fail': 'Failed to add tenant, maybe database operation error or tenant with the same name already exists',
                'please_enter_tenant_name': 'Please enter tenant name',
                'please_select_tenant_type': 'Please select tenant type',
                'please_enter_contact_person': 'Please enter contact person',
                'please_enter_phone': 'Please enter phone number',
                'export_tenant_success': 'Export successful!\nFile path: {0}',
                'export_tenant_fail': 'Failed to export tenant information: {0}',
                'import_tenant_fail': 'Failed to import tenant information: {0}',
                'file_format_error': 'Invalid file format, missing required columns: {0}',
                'tenant_exists': 'Tenant \'{0}\' already exists',
                'import_progress': 'Import Progress',
                'preparing_import': 'Preparing import...',
                'importing_row': 'Importing row {0}/{1}...',
                'import_result': 'Import Result',
                'import_completed': 'Import completed!\n\nTotal: {0} rows\nSuccess: {1} rows\nFailed: {2} rows\n',
                'failed_reasons': 'Failed reasons:',
                'more_failed_reasons': '... {0} more failed reasons not shown\n',
                'saving_tenant': 'Saving tenant information...',
                'cannot_get_tenant_id': 'Failed to get tenant ID',
                'cannot_find_tenant_info': 'Cannot find tenant information',
                'save_tenant_exception': 'Exception occurred when saving tenant information: {0}',
                'tenant_id': 'Tenant ID',
                'create_time': 'Create Time',
                'tenant_information': 'Tenant Information',
                'select_tenant_excel_file': 'Select tenant Excel file to import',
                'fail': 'Fail',
                'success': 'Success',
                'meter_management': 'Meter Management',
                'meter_no': 'Meter No',
                'water_meter': 'Water',
                'electric_meter': 'Electric',
                'meter_type': 'Meter Type',
                'tenant': 'Tenant',
                'location': 'Location',
                'initial_reading': 'Initial Reading',
                'status': 'Status',
                'normal': 'Normal',
                'damaged': 'Damaged',
                'replaced': 'Replaced',
                'meter_details': 'Meter Details',
                'add_meter': 'Add Meter',
                'edit_meter': 'Edit Meter',
                'delete_meter': 'Delete Meter',
                'refresh_list': 'Refresh List',
                'export_meter': 'Export Meters',
                'import_meter': 'Import Meters',
                'load_tenant_list_exception': 'Exception occurred when loading tenant list: {0}',
                'search_meter_exception': 'Exception occurred when searching meters: {0}',
                'failed_to_get_meter_id': 'Failed to get meter ID',
                'data_synchronizing': 'Data is synchronizing...',
                'failed_to_fill_form': 'Exception occurred when filling form: {0}',
                'please_select_meter_edit': 'Please select a meter to edit',
                'please_select_meter_delete': 'Please select a meter to delete',
                'failed_to_find_meter': 'Cannot find meter information to delete',
                'confirm_delete_meter': 'Are you sure to delete meter \'{0}\'?\nCannot recover after deletion.',
                'meter_delete_success': 'Meter \'{0}\' deleted successfully',
                'meter_delete_fail': 'Failed to delete meter, please check if this meter has associated reading records or charge records',
                'delete_meter_exception': 'Exception occurred when deleting meter: {0}',
                'load_meter_list_exception': 'Exception occurred when loading meter list: {0}',
                'list_refreshed': 'List refreshed',
                'search_completed': 'Search completed, found {0} records',
                'temporary_message': 'Message',
                'please_enter_meter_no': 'Please enter meter no',
                'please_select_meter_type': 'Please select meter type',
                'please_select_tenant': 'Please select tenant',
                'please_enter_location': 'Please enter location',
                'initial_reading_must_be_number': 'Initial reading must be a number',
                'please_select_status': 'Please select status',
                'please_select_valid_tenant': 'Please select a valid tenant',
                'meter_no_exists': 'Meter no \'{0}\' already exists, please use another meter no',
                'meter_update_success': 'Meter \'{0}\' updated successfully',
                'meter_update_fail': 'Failed to update meter information',
                'meter_add_success': 'Meter \'{0}\' added successfully',
                'meter_add_fail': 'Failed to add meter',
                'save_meter_exception': 'Exception occurred when saving meter information: {0}',
                'meter_information': 'Meter Information',
                'meter_id': 'Meter ID',
                'create_time': 'Create Time',
                'export_meter_success': 'Export successful!\nFile path: {0}',
                'export_meter_fail': 'Failed to export meter information: {0}',
                'import_meter_fail': 'Failed to import meter information: {0}',
                'select_meter_excel_file': 'Select meter Excel file to import',
                'file_format_error': 'Invalid file format, missing required columns: {0}',
                'meter_no_cannot_be_empty': 'Meter no cannot be empty',
                'meter_type_must_be_water_or_electric': 'Meter type must be \'Water\' or \'Electric\'',
                'tenant_cannot_be_empty': 'Tenant cannot be empty',
                'tenant_not_exist': 'Tenant \'{0}\' does not exist, please add the tenant first',
                'location_cannot_be_empty': 'Location cannot be empty',
                'initial_reading_must_be_a_number': 'Initial reading must be a number',
                'status_must_be_normal_damaged_or_replaced': 'Status must be \'Normal\', \'Damaged\' or \'Replaced\'',
                'import_progress': 'Import Progress',
                'preparing_import': 'Preparing import...',
                'importing_row': 'Importing row {0}/{1}...',
                'import_result': 'Import Result',
                'import_completed': 'Import completed!\n\nTotal: {0} rows\nSuccess: {1} rows\nFailed: {2} rows\n',
                'failed_reasons': 'Failed reasons:',
                'more_failed_reasons': '... {0} more failed reasons not shown\n',
                # Button text
                'button_ok': 'OK',
                'button_cancel': 'Cancel',
                'button_yes': 'Yes',
                'button_no': 'No',
                # Prompt types
                'info': 'Info',
                'warning': 'Warning',
                'error': 'Error',
                # Price management related
                'water': 'Water',
                'electricity': 'Electricity',
                'resource_type': 'Resource Type',
                'tenant_type': 'Tenant Type',
                'price': 'Price',
                'office': 'Office',
                'storefront': 'Storefront',
                'all': 'All',
                'effective_start_date': 'Effective Start Date',
                'effective_end_date': 'Effective End Date',
                'price_details': 'Price Details',
                'date_format': 'Format',
                'date_format_yyyy_mm_dd': '(Format: YYYY-MM-DD)',
                'leave_empty_for_permanent': 'Leave empty for permanent',
                'price_list_refresh_fail': 'Failed to refresh price list',
                'cannot_find_price_details': 'Cannot find price details',
                'please_select_price_edit': 'Please select price to edit',
                'entered_edit_mode': 'Entered edit mode, editing',
                'price_record': 'Price Record',
                'please_modify_form_and_save': 'Please modify the form on the right and click save button',
                'please_select_price_delete': 'Please select price to delete',
                'yuan': 'Yuan',
                'ton': 'Ton',
                'kwh': 'kWh',
                'permanent': 'Permanent',
                'delete_irreversible': 'Cannot recover after deletion,',
                'continue': 'Continue?',
                'delete_success': 'Delete successful',
                'database_error': ', maybe database operation error',
                'delete_price_exception': 'Exception occurred when deleting price',
                'please_select_resource_type': 'Please select resource type',
                'please_select_tenant_type': 'Please select tenant type',
                'please_enter_price': 'Please enter price',
                'price_cannot_be_negative': 'Price cannot be negative',
                'price_cannot_be_zero': 'Price cannot be zero',
                'price_must_be_valid_number': 'Price must be a valid number',
                'please_enter_effective_start_date': 'Please enter effective start date',
                'effective_start_date_format_error': 'Invalid effective start date format',
                'correct_format': 'Correct format',
                'effective_end_date_format_error': 'Invalid effective end date format',
                'start_date_cannot_be_later_than_end_date': 'Effective start date cannot be later than effective end date',
                'update_success': 'Update successful',
                'update_fail': 'Update failed',
                'add_success': 'Add successful',
                'add_fail': 'Add failed',
                'database_error_or_duplicate': ', maybe database operation error or duplicate price record exists',
                'save_price_exception': 'Exception occurred when saving price information',
                # Charge management related
                'calculate_charges': 'Calculate Charges',
                'delete_records': 'Delete Records',
                'unpaid': 'Unpaid',
                'paid': 'Paid',
                'partially_paid': 'Partially Paid',
                'water_usage': 'Water Usage',
                'electricity_usage': 'Electricity Usage',
                'water_charge': 'Water Charge',
                'electricity_charge': 'Electricity Charge',
                'total_charge': 'Total Charge',
                'paid_amount': 'Paid Amount',
                'due_amount': 'Due Amount',
                'charge_details': 'Charge Details',
                'total': 'Total',
                'records': 'records',
                'total_water_charge': 'Total Water Charge Amount',
                'total_electricity_charge': 'Total Electricity Charge Amount',
                'total_paid_amount': 'Total Paid Amount',
                'total_due_amount': 'Total Due Amount',
                'unknown_tenant': 'Unknown Tenant',
                'charge_month': 'Charge Month',
                'water_charge_details': 'Water Charge Details',
                'electricity_charge_details': 'Electricity Charge Details',
                'usage': 'Usage',
                'units': 'Units',
                'unit': 'Unit',
                'amount': 'Amount',
                'charge_status': 'Charge Status',
                'loading': 'Loading',
                'please_wait_getting_charge_details': 'Please wait, getting charge details',
                'please_select_records_to_delete': 'Please select records to delete',
                'record': 'Record',
                'status_is_paid_cannot_delete': 'Status is paid, cannot delete',
                'status_is_partially_paid_cannot_delete': 'Status is partially paid, cannot delete',
                'related_payment_records': 'Related payment records',
                'has_related_payment_records_cannot_delete': 'Has related payment records, cannot delete',
                'charge_record_status_is_paid_cannot_delete': 'This charge record status is paid, cannot delete',
                'charge_record_status_is_partially_paid_cannot_delete': 'This charge record status is partially paid, cannot delete',
                'record_has_related_payment_records_not_allowed_delete': 'This record has related payment records, not allowed to delete',
                'operation_tip': 'Operation Tip',
                'confirm_delete_selected_records': 'Are you sure to delete selected',
                'this_operation_cannot_be_undone': 'This operation cannot be undone!',
                'delete_result': 'Delete Result',
                'delete_completed': 'Delete Completed',
                'successfully_deleted': 'Successfully deleted',
                'charge_calculation_completed': 'Charge calculation completed',
                'new_added': 'New Added',
                'updated': 'Updated',
                'households': 'Households',
                'calculation_result': 'Calculation Result',
                # Payment management related
                'charge_information': 'Charge Information',
                'charge_query': 'Charge Query',
                'payment_query': 'Payment Query',
                'query_arrears': 'Arrears Query',
                'delete_payment': 'Delete Payment',
                'generate_payment_receipt': 'Payment Receipt',
                'payment_date': 'Payment Date',
                'settlement_date': 'Settlement Time',
                'payment_method': 'Payment Method',
                'cash': 'Cash',
                'bank_transfer': 'Bank Transfer',
                'wechat': 'WeChat',
                'alipay': 'Alipay',
                'payer': 'Payer',
                'failed_to_load_tenant_data': 'Failed to load tenant data',
                'failed_to_load_form_tenant_data': 'Failed to load form tenant data',
                'invalid_payment_record_id': 'Invalid payment record ID',
                'please_select_payment_to_delete': 'Please select payment record to delete',
                'operation_restriction': 'Operation Restriction',
                'payment_record_settled_cannot_delete': 'This payment record has been settled, cannot delete',
                'confirm_delete_this_payment_record': 'Are you sure to delete this payment record',
                'payment_record_deleted_successfully_status_updated': 'Payment record deleted successfully, and charge record status updated',
                'failed_to_delete_payment_record': 'Failed to delete payment record',
                'please_select_tenant': 'Please select tenant',
                'please_select_charge_month': 'Please select charge month',
                'please_enter_amount': 'Please enter payment amount',
                'amount_must_be_number': 'Payment amount must be a number',
                'amount_must_be_greater_than_zero': 'Payment amount must be greater than 0',
                'please_enter_payment_date': 'Please enter payment date',
                'please_select_payment_method': 'Please select payment method',
                'please_enter_payer': 'Please enter payer',
                'please_select_valid_tenant': 'Please select a valid tenant',
                'tenant_no_charge_for_month': 'No charge records for this tenant in selected month',
                'payment_record_updated_successfully': 'Payment record updated successfully',
                'failed_to_update_payment_record': 'Failed to update payment record',
                'payment_record_added_successfully': 'Payment record added successfully',
                'failed_to_add_payment_record': 'Failed to add payment record',
                # Main window related
                'menu_file': 'File',
                'menu_base_info': 'Basic Information',
                'menu_meter_reading': 'Reading Entry',
                'menu_charge_calculation': 'Charge Calculation',
                'menu_payment_entry': 'Payment Entry',
                'menu_settlement': 'Settlement',
                'menu_monthly_report': 'Report Center',
                'menu_data_backup': 'Data Backup',
                'menu_data_restore': 'Data Restore',
                'menu_data_initialization': 'Data Initialization',
                'welcome': 'Welcome',
                'data_restore': 'Data Restore',
                'select_backup_file': 'Select backup file:',
                'backup_date': 'Backup Date',
                'form_title_tenant_management': 'Tenant Management',
                'form_title_meter_management': 'Meter Management',
                'form_title_price_management': 'Price Management',
                'form_title_reading_entry': 'Reading Entry',
                'form_title_charge_calculation': 'Charge Calculation',
                'form_title_payment_entry': 'Payment Entry',
                'form_title_settlement_management': 'Settlement Management',
                'form_title_report_management': 'Report Center',
                'form_title_user_management': 'User Management',
                'form_title_system_settings': 'System Settings',
                'notes': 'Notes',
                'payment_receipt': 'Payment Receipt',
                'arrears_query': 'Arrears Query',
                'total_arrears': 'Total Arrears',
                'arrears_count': 'Arrears Households',
                'close': 'Close',
                'format_error': 'Format Error',
                'month_format_yyyy_mm': 'Invalid month format, should be YYYY-MM format',
                'auto_match_charge_fail': 'Failed to auto match charge records',
                'calculate_total_paid_fail': 'Failed to calculate total paid amount',
                'update_charge_status_fail': 'Failed to update charge status',
                'load_charge_months_fail': 'Failed to load charge months',
                'deleting': 'Deleting',
                'updating': 'Updating',
                'querying': 'Querying',
                'filename': 'Filename',
                'unknown_date': 'Unknown Date',
                'button_restore': 'Restore',
                'unknown_tenant': 'Unknown Tenant',
                'menu_user_management': 'User Management',
                'total_arrears': 'Total Arrears Amount',
                'select_all': 'Select All',
                'import_to_payment': 'Import to Payment',
                'please_select_records_to_import': 'Please select records to import',
                'payment_records': 'Arrears Record Count',
                'records': 'records',
                'refreshed': 'Refreshed',
                'total_loaded': 'Total loaded',
                'failed_to_refresh': 'Refresh',
                'failed_to_update_stats': 'Failed to update statistical labels',
                # Settlement management related
                'settlement_management': 'Settlement Management',
                'settle_month': 'Settlement Month',
                'search': 'Search',
                'reset': 'Reset',
                'add_settlement': 'Add Settlement',
                'edit_settlement': 'Edit Settlement',
                'delete_settlement': 'Delete Settlement',
                'generate_settlement_report': 'Generate Settlement Report',
                'refresh_list': 'Refresh List',
                'serial': 'Serial',
                'settle_date': 'Settlement Date',
                'total_amount': 'Settlement Amount',
                'cashier': 'Cashier',
                'notes': 'Notes',
                'settlement_details': 'Settlement Details',
                'calculate_monthly_received': 'Calculate Monthly Received Amount',
                'save': 'Save',
                'cancel': 'Cancel',
                'operation_guide': 'Operation Guide',
                'guide_step_1': '1. Enter settlement month',
                'guide_step_2': '2. Click "Calculate Monthly Received Amount" button to auto calculate amount',
                'guide_step_3': '3. Fill in settlement date, cashier and other information',
                'guide_step_4': '4. Click "Save" button to complete',
                'edit_mode': 'Entered edit mode',
                'editing': 'Editing',
                'please_select_settlement_to_edit': 'Please select settlement to edit',
                'data_expired_please_refresh': 'Cannot find settlement record, maybe data expired, please refresh list and try again',
                'settlement_id_invalid': 'Invalid settlement record ID, please refresh list and try again',
                'please_select_settlement_to_delete': 'Please select settlement to delete',
                'confirm_delete_settlement': 'Confirm Delete',
                'delete_irreversible': 'Cannot recover after deletion, continue?',
                'settlement_deleted_successfully': 'Settlement deleted successfully',
                'settlement_delete_failed': 'Failed to delete settlement',
                'please_enter_settlement_month': 'Please enter settlement month',
                'settle_month_format_error': 'Invalid settlement month format, should be YYYY-MM format (e.g. 2025-12)',
                'monthly_received_calculation_result': '{0} Monthly Received Amount Calculation Result',
                'total_received_amount': 'Total Received Amount',
                'payment_count': 'Payment Count',
                'payment_method_distribution': 'Payment Method Distribution',
                'no_data': 'No Data',
                'calculation_result_filled': 'Calculation result has been auto filled to settlement amount field',
                'manual_adjustment_allowed': 'You can manually adjust amount if needed',
                'settlement_amount_cannot_be_negative': 'Settlement amount cannot be negative',
                'settlement_amount_must_be_valid_number': 'Settlement amount must be a valid number',
                'please_enter_settle_date': 'Please enter settlement date',
                'settle_date_format_error': 'Invalid settlement date format, should be YYYY-MM-DD format (e.g. 2025-12-31)',
                'settle_date_cannot_be_before_month_start': 'Settlement date cannot be earlier than {0}-01',
                'settle_date_cannot_be_after_current_date': 'Settlement date cannot be later than current date',
                'please_enter_cashier_name': 'Please enter cashier name',
                'cashier_name_too_long': 'Cashier name cannot exceed 50 characters',
                'notes_too_long': 'Notes cannot exceed 200 characters',
                'settlement_month_already_exists': 'Settlement record for {0} already exists, cannot modify to this month',
                'settlement_update_success': 'Settlement record updated successfully\nUpdated settlement record for {0}',
                'settlement_add_success': 'Settlement record added successfully\nAdded settlement record for {0}',
                'database_operation_failed': 'Database operation failed, cannot {0} settlement record',
                'confirm_generate_report': 'Generate settlement report for {0}?',
                'settlement_report_success': 'Settlement report has been successfully exported to\n{0}',
                'settlement_report_failed': 'Failed to generate settlement report: {0}',
                'generate_time': 'Generate Time',
                'settlement_summary': '{0} Settlement Summary',
                'monthly_settlement_report': '{0} Monthly Settlement Report',
                'settlement_details_sheet': '{0} Settlement Details',
                'payment_details_sheet': '{0} Payment Details',
                'item': 'Item',
                'amount_quantity': 'Amount/Quantity',
                'description': 'Description',
                'total_charge_amount': 'Total Charge Amount',
                'paid_amount': 'Paid Amount',
                'arrears_amount': 'Arrears Amount',
                'paid_households': 'Paid Households',
                'total_households': 'Total Households',
                'payment_rate': 'Payment Rate',
                'tenant_name': 'Tenant Name',
                'receipt_no': 'Receipt No',
                'collector': 'Collector',
                'unknown_payer': 'Unknown Collector',
                # Help documentation common questions
                'technical_support': 'Technical Support',
                'contact_info': 'Contact Info',
                'official_website': 'Official Website',
                'online_docs': 'Online Docs',
                'tenant_management_desc': 'Tenant management module is used to add, edit and delete tenant information, including tenant name, contact information, rental area, etc. You can enter this module through the "Tenant Management" menu item in the left menu.',
                'meter_management_desc': 'Meter management module is used to add, edit and delete meter information, including water meter number, electricity meter number, tenant information, etc. You can enter this module through the "Meter Management" menu item in the left menu.',
                'reading_management_desc': 'Reading management module is used to enter and query meter reading data, including reading date, water meter reading, electricity meter reading, etc. You can enter this module through the "Reading Management" menu item in the left menu.',
                'charge_management_desc': 'Charge management module is used to calculate and manage tenant water and electricity charges, the system will automatically calculate charges based on reading data and price settings. You can enter this module through the "Charge Management" menu item in the left menu.',
                'payment_management_desc': 'Payment management module is used to enter and query payment data, including payment date, payment amount, payment method, etc. You can enter this module through the "Payment Management" menu item in the left menu.',
                'report_management_desc': 'Report management module is used to generate various reports, including monthly reports, tenant detail reports, payment stat reports, etc. You can enter this module through the "Report Management" menu item in the left menu.',
                # FAQ
                'faq_how_to_view_history_charges': 'How to view historical charge records?',
                'faq_how_to_add_meter': 'How to add a new meter?',
                'faq_how_to_modify_tenant_info': 'How to modify tenant information?',
                'faq_how_to_generate_tenant_report': 'How to generate tenant detail report?',
                'faq_how_to_set_system_params': 'How to set system parameters?',
                'faq_answer_view_history_charges': 'To view historical charge records, you can enter the charge management module through the left menu. In this module, you can select tenant and time range, then view historical charge records of the tenant.',
                'faq_answer_add_meter': 'To add a new meter, you can enter the meter management module through the left menu. In this module, you can add new meter information, including meter number, type, tenant, etc.',
                'faq_answer_modify_tenant_info': 'To modify tenant information, you can enter the tenant management module through the left menu. In this module, you can find the tenant to modify, then click edit button to modify tenant information.',
                'faq_answer_generate_tenant_report': 'To generate tenant detail report, you can enter the report center module through the left menu. In this module, you can select "Tenant Detail Report" type, then select tenant and time range, click "Generate Report" button to generate.',
                'faq_answer_set_system_params': 'To set system parameters, you can enter the system settings module through the left menu. In this module, you can set various system parameters, such as reading date, price settings, etc.',
                # Report related
                'monthly_water_electricity_report': 'Monthly Water and Electricity Report',
                'report_month': 'Report Month',
                'by_tenant': 'By Tenant',
                'by_type': 'By Type',
                'unknown_type': 'Unknown Type',
                'unknown_tenant': 'Unknown Tenant',
                'tenant_water_electricity_detail_report': 'Tenant Water and Electricity Detail Report',
                'payment_stat_report_title': 'Payment Stat Report',
                'water_electricity_settlement_report': 'Water and Electricity Settlement Report',
                'payment_statistics': 'Payment Statistics',
                'monthly_total_payment': 'Monthly Total Payment',
                'payment_record_count': 'Payment Record Count',
                'statistics_by': 'By',
                'statistical_item': 'Statistical Item',
                'amount_yuan': 'Amount (Yuan)',
                'percentage': 'Percentage',
                'settlement_info': 'Settlement Information',
                'no_settlement_this_month': 'No settlement this month',
                'suggested_settlement_amount': 'Suggested Settlement Amount',
                # Export related
                'export_excel_report': 'Export Excel Report',
                'excel_report_successfully_exported_to': 'Excel report has been successfully exported to',
                'failed_to_export_excel_report': 'Failed to export Excel report',
                # Chart related
                'chart_area': 'Chart Area',
                'generating_report_please_wait': 'Generating report, please wait...',
                # Database and status related
                'database': 'Database',
                'data_status': 'Data Status',
                'normal': 'Normal',
                # Software Information
                'software_info': 'Software Information',
                'software_brand': 'Software Brand',
                'software_name': 'Software Name',
                'software_version': 'Software Version',
                'developer': 'Developer',
                'development_date': 'Development Date'
            }
        }
    
    def get_text(self, key: str) -> str:
        """
        获取指定键的文本
        :param key: 文本键名
        :return: 对应语言的文本
        """
        if key in self.language_resources[self.current_language]:
            return self.language_resources[self.current_language][key]
        return key
    
    def subscribe(self, callback: Callable[[str, str], None]) -> None:
        """
        订阅语言变化事件
        :param callback: 语言变化时调用的回调函数
        """
        if callback not in self._subscribers:
            self._subscribers.append(callback)
    
    def unsubscribe(self, callback: Callable[[str, str], None]) -> None:
        """
        取消订阅语言变化事件
        :param callback: 要取消的回调函数
        """
        if callback in self._subscribers:
            self._subscribers.remove(callback)
    
    def set_language(self, language_code: str) -> None:
        """
        设置当前语言
        :param language_code: 语言代码，如 'zh_CN' 或 'en_US'
        """
        if language_code in self.language_resources and language_code != self.current_language:
            old_language = self.current_language
            self.current_language = language_code
            # 通知所有订阅者语言已变化
            self._notify_subscribers(old_language, self.current_language)
        elif language_code not in self.language_resources:
            print(f"Unsupported language: {language_code}, using default language")
    
    def _notify_subscribers(self, old_language: str, new_language: str) -> None:
        """
        通知所有订阅者语言已变化
        :param old_language: 旧语言代码
        :param new_language: 新语言代码
        """
        for callback in self._subscribers:
            try:
                callback(old_language, new_language)
            except Exception as e:
                print(f"Error in language change callback: {e}")
    
    def check_resource_completeness(self) -> Dict[str, List[str]]:
        """
        检查所有语言资源的完整性，返回缺失的键
        :return: 包含每种语言缺失键的字典
        """
        missing_keys = {}
        
        # 获取所有语言代码
        languages = list(self.language_resources.keys())
        
        if not languages:
            return missing_keys
        
        # 以第一种语言为基准，检查其他语言是否缺失键
        base_language = languages[0]
        base_keys = set(self.language_resources[base_language].keys())
        
        for lang in languages:
            if lang == base_language:
                continue
            
            current_keys = set(self.language_resources[lang].keys())
            missing = base_keys - current_keys
            if missing:
                missing_keys[lang] = sorted(list(missing))
        
        return missing_keys
    
    def validate_resources(self) -> bool:
        """
        验证语言资源的完整性
        :return: 资源是否完整
        """
        missing = self.check_resource_completeness()
        
        if missing:
            print("语言资源缺失警告:")
            for lang, keys in missing.items():
                print(f"  {lang} 缺失 {len(keys)} 个键: {', '.join(keys[:5])}{'...' if len(keys) > 5 else ''}")
            return False
        else:
            print("所有语言资源完整")
            return True